import '../models/affiliation_model.dart';

class AffiliationsSeed {
  static const List<AffiliationModel> affiliations = [
    // Malaysia — Public
    AffiliationModel(id: 'um', name: 'University of Malaya', type: 'university'),
    AffiliationModel(id: 'usm', name: 'Universiti Sains Malaysia', type: 'university'),
    AffiliationModel(id: 'utm', name: 'Universiti Teknologi Malaysia', type: 'university'),
    AffiliationModel(id: 'ukm', name: 'Universiti Kebangsaan Malaysia', type: 'university'),
    AffiliationModel(id: 'upm', name: 'Universiti Putra Malaysia', type: 'university'),
    AffiliationModel(id: 'uitm', name: 'Universiti Teknologi MARA', type: 'university'),
    AffiliationModel(id: 'uum', name: 'Universiti Utara Malaysia', type: 'university'),
    AffiliationModel(id: 'ums', name: 'Universiti Malaysia Sabah', type: 'university'),
    AffiliationModel(id: 'unimas', name: 'Universiti Malaysia Sarawak', type: 'university'),
    AffiliationModel(id: 'upsi', name: 'Universiti Pendidikan Sultan Idris', type: 'university'),
    AffiliationModel(id: 'uthm', name: 'Universiti Tun Hussein Onn Malaysia', type: 'university'),
    AffiliationModel(id: 'utem', name: 'Universiti Teknikal Malaysia Melaka', type: 'university'),
    AffiliationModel(id: 'umpsa', name: 'Universiti Malaysia Pahang Al-Sultan Abdullah', type: 'university'),
    AffiliationModel(id: 'upnm', name: 'Universiti Pertahanan Nasional Malaysia', type: 'university'),
    AffiliationModel(id: 'usim', name: 'Universiti Sains Islam Malaysia', type: 'university'),
    AffiliationModel(id: 'unisza', name: 'Universiti Sultan Zainal Abidin', type: 'university'),
    AffiliationModel(id: 'umt', name: 'Universiti Malaysia Terengganu', type: 'university'),
    AffiliationModel(id: 'umk', name: 'Universiti Malaysia Kelantan', type: 'university'),
    AffiliationModel(id: 'unimap', name: 'Universiti Malaysia Perlis', type: 'university'),
    AffiliationModel(id: 'iium', name: 'International Islamic University Malaysia', type: 'university'),
    // Malaysia — Private
    AffiliationModel(id: 'utp', name: 'Universiti Teknologi Petronas', type: 'university'),
    AffiliationModel(id: 'taylors', name: "Taylor's University", type: 'university'),
    AffiliationModel(id: 'sunway', name: 'Sunway University', type: 'university'),
    AffiliationModel(id: 'monash-my', name: 'Monash University Malaysia', type: 'university'),
    AffiliationModel(id: 'nottingham-my', name: 'University of Nottingham Malaysia', type: 'university'),
    AffiliationModel(id: 'apu', name: 'Asia Pacific University', type: 'university'),
    AffiliationModel(id: 'ucsi', name: 'UCSI University', type: 'university'),
    AffiliationModel(id: 'mmu', name: 'Multimedia University', type: 'university'),
    AffiliationModel(id: 'utar', name: 'Universiti Tunku Abdul Rahman', type: 'university'),
    AffiliationModel(id: 'uniten', name: 'Universiti Tenaga Nasional', type: 'university'),
    AffiliationModel(id: 'unikl', name: 'Universiti Kuala Lumpur', type: 'university'),
    AffiliationModel(id: 'help', name: 'HELP University', type: 'university'),
    AffiliationModel(id: 'inti', name: 'INTI International University', type: 'university'),
    AffiliationModel(id: 'mahsa', name: 'MAHSA University', type: 'university'),
    AffiliationModel(id: 'segi', name: 'SEGi University', type: 'university'),
    AffiliationModel(id: 'uow-kdu', name: 'UOW Malaysia KDU', type: 'university'),
    AffiliationModel(id: 'limkokwing', name: 'Limkokwing University', type: 'university'),
    AffiliationModel(id: 'tar-umt', name: 'TAR UMT', type: 'university'),
    AffiliationModel(id: 'msu', name: 'Management and Science University', type: 'university'),
    AffiliationModel(id: 'heriot-watt-my', name: 'Heriot-Watt University Malaysia', type: 'university'),
    AffiliationModel(id: 'reading-my', name: 'University of Reading Malaysia', type: 'university'),
    AffiliationModel(id: 'swinburne-sarawak', name: 'Swinburne University of Technology Sarawak', type: 'university'),
    AffiliationModel(id: 'curtin-my', name: 'Curtin University Malaysia', type: 'university'),
    AffiliationModel(id: 'newcastle-my', name: 'Newcastle University Medicine Malaysia', type: 'university'),
    AffiliationModel(id: 'rumc', name: 'RUMC', type: 'university'),
    AffiliationModel(id: 'unitar', name: 'UNITAR International University', type: 'university'),
    AffiliationModel(id: 'oum', name: 'Open University Malaysia', type: 'university'),
    AffiliationModel(id: 'wawasan', name: 'Wawasan Open University', type: 'university'),
    AffiliationModel(id: 'aeu', name: 'Asia e University', type: 'university'),
    AffiliationModel(id: 'unisel', name: 'Universiti Selangor', type: 'university'),
    AffiliationModel(id: 'nilai', name: 'Universiti Nilai', type: 'university'),
    AffiliationModel(id: 'manipal-my', name: 'Manipal University College Malaysia', type: 'university'),
    AffiliationModel(id: 'kpj', name: 'KPJ Healthcare University', type: 'university'),
    AffiliationModel(id: 'cucms', name: 'Cyberjaya University College of Medical Sciences', type: 'university'),
    AffiliationModel(id: 'lincoln', name: 'Lincoln University College', type: 'university'),
    AffiliationModel(id: 'aimst', name: 'AIMST University', type: 'university'),
    AffiliationModel(id: 'al-bukhary', name: 'Albukhary International University', type: 'university'),
    AffiliationModel(id: 'bac', name: 'BAC University', type: 'university'),
    AffiliationModel(id: 'berjaya', name: 'Berjaya University College', type: 'university'),
    AffiliationModel(id: 'binary', name: 'Binary University', type: 'university'),
    AffiliationModel(id: 'city-u', name: 'City University Malaysia', type: 'university'),
    AffiliationModel(id: 'iukl', name: 'Infrastructure University Kuala Lumpur', type: 'university'),
    AffiliationModel(id: 'must', name: 'Malaysia University of Science & Technology', type: 'university'),
    AffiliationModel(id: 'newera', name: 'New Era University College', type: 'university'),
    AffiliationModel(id: 'perdana', name: 'Perdana University', type: 'university'),
    AffiliationModel(id: 'quest', name: 'Quest International University', type: 'university'),
    AffiliationModel(id: 'saito', name: 'Saito University College', type: 'university'),
    AffiliationModel(id: 'unirazak', name: 'Universiti Tun Abdul Razak', type: 'university'),
    AffiliationModel(id: 'politeknik-my', name: 'Politeknik Malaysia', type: 'university'),
    // Singapore
    AffiliationModel(id: 'nus', name: 'National University of Singapore', type: 'university'),
    AffiliationModel(id: 'ntu', name: 'Nanyang Technological University', type: 'university'),
    AffiliationModel(id: 'smu', name: 'Singapore Management University', type: 'university'),
    AffiliationModel(id: 'sutd', name: 'Singapore University of Technology and Design', type: 'university'),
    AffiliationModel(id: 'sit', name: 'Singapore Institute of Technology', type: 'university'),
    AffiliationModel(id: 'suss', name: 'Singapore University of Social Sciences', type: 'university'),
    AffiliationModel(id: 'sim', name: 'SIM (Singapore Institute of Management)', type: 'university'),
    AffiliationModel(id: 'ngee-anne-poly', name: 'Ngee Ann Polytechnic', type: 'university'),
    AffiliationModel(id: 'sg-poly', name: 'Singapore Polytechnic', type: 'university'),
    AffiliationModel(id: 'temasek-poly', name: 'Temasek Polytechnic', type: 'university'),
    AffiliationModel(id: 'republic-poly', name: 'Republic Polytechnic', type: 'university'),
    AffiliationModel(id: 'nanyang-poly', name: 'Nanyang Polytechnic', type: 'university'),
    AffiliationModel(id: 'lasalle', name: 'LASALLE College of the Arts', type: 'university'),
    AffiliationModel(id: 'nafa', name: 'Nanyang Academy of Fine Arts', type: 'university'),
    AffiliationModel(id: 'jcu-sg', name: 'James Cook University Singapore', type: 'university'),
    AffiliationModel(id: 'curtin-sg', name: 'Curtin Singapore', type: 'university'),
    AffiliationModel(id: 'psb', name: 'PSB Academy', type: 'university'),
    AffiliationModel(id: 'kaplan-sg', name: 'Kaplan Singapore', type: 'university'),
    AffiliationModel(id: 'mdis', name: 'MDIS', type: 'university'),
    AffiliationModel(id: 'ite-sg', name: 'Institute of Technical Education', type: 'university'),
    AffiliationModel(id: 'shatec', name: 'SHATEC', type: 'university'),
    AffiliationModel(id: 'duke-nus', name: 'Duke-NUS Medical School', type: 'university'),
    // Indonesia — Public
    AffiliationModel(id: 'ui', name: 'Universitas Indonesia', type: 'university'),
    AffiliationModel(id: 'itb', name: 'Institut Teknologi Bandung', type: 'university'),
    AffiliationModel(id: 'ugm', name: 'Universitas Gadjah Mada', type: 'university'),
    AffiliationModel(id: 'unair', name: 'Universitas Airlangga', type: 'university'),
    AffiliationModel(id: 'ipb', name: 'IPB University', type: 'university'),
    AffiliationModel(id: 'undip', name: 'Universitas Diponegoro', type: 'university'),
    AffiliationModel(id: 'unpad', name: 'Universitas Padjadjaran', type: 'university'),
    AffiliationModel(id: 'ubraw', name: 'Universitas Brawijaya', type: 'university'),
    AffiliationModel(id: 'uns', name: 'Universitas Sebelas Maret', type: 'university'),
    AffiliationModel(id: 'uny', name: 'Universitas Negeri Yogyakarta', type: 'university'),
    AffiliationModel(id: 'its', name: 'Institut Teknologi Sepuluh Nopember', type: 'university'),
    AffiliationModel(id: 'unand', name: 'Universitas Andalas', type: 'university'),
    AffiliationModel(id: 'unhas', name: 'Universitas Hasanuddin', type: 'university'),
    AffiliationModel(id: 'usu', name: 'Universitas Sumatera Utara', type: 'university'),
    AffiliationModel(id: 'upi', name: 'Universitas Pendidikan Indonesia', type: 'university'),
    AffiliationModel(id: 'unnes', name: 'Universitas Negeri Semarang', type: 'university'),
    AffiliationModel(id: 'unesa', name: 'Universitas Negeri Surabaya', type: 'university'),
    AffiliationModel(id: 'unj', name: 'Universitas Negeri Jakarta', type: 'university'),
    AffiliationModel(id: 'unimed', name: 'Universitas Negeri Medan', type: 'university'),
    AffiliationModel(id: 'unp', name: 'Universitas Negeri Padang', type: 'university'),
    AffiliationModel(id: 'unm', name: 'Universitas Negeri Makassar', type: 'university'),
    AffiliationModel(id: 'unram', name: 'Universitas Mataram', type: 'university'),
    AffiliationModel(id: 'unlam', name: 'Universitas Lambung Mangkurat', type: 'university'),
    AffiliationModel(id: 'unsri', name: 'Universitas Sriwijaya', type: 'university'),
    AffiliationModel(id: 'unri', name: 'Universitas Riau', type: 'university'),
    AffiliationModel(id: 'unud', name: 'Universitas Udayana', type: 'university'),
    AffiliationModel(id: 'uncen', name: 'Universitas Cenderawasih', type: 'university'),
    AffiliationModel(id: 'untad', name: 'Universitas Tadulako', type: 'university'),
    AffiliationModel(id: 'unsrat', name: 'Universitas Sam Ratulangi', type: 'university'),
    AffiliationModel(id: 'unkhair', name: 'Universitas Khairun', type: 'university'),
    AffiliationModel(id: 'unpatti', name: 'Universitas Pattimura', type: 'university'),
    AffiliationModel(id: 'undana', name: 'Universitas Nusa Cendana', type: 'university'),
    AffiliationModel(id: 'usk', name: 'Universitas Syiah Kuala', type: 'university'),
    AffiliationModel(id: 'unsoed', name: 'Universitas Jenderal Soedirman', type: 'university'),
    AffiliationModel(id: 'unila', name: 'Universitas Lampung', type: 'university'),
    AffiliationModel(id: 'unib', name: 'Universitas Bengkulu', type: 'university'),
    AffiliationModel(id: 'unja', name: 'Universitas Jambi', type: 'university'),
    AffiliationModel(id: 'unimal', name: 'Universitas Malikussaleh', type: 'university'),
    AffiliationModel(id: 'untan', name: 'Universitas Tanjungpura', type: 'university'),
    AffiliationModel(id: 'unmul', name: 'Universitas Mulawarman', type: 'university'),
    AffiliationModel(id: 'unipa', name: 'Universitas Papua', type: 'university'),
    AffiliationModel(id: 'uho', name: 'Universitas Halu Oleo', type: 'university'),
    AffiliationModel(id: 'upr', name: 'Universitas Palangka Raya', type: 'university'),
    AffiliationModel(id: 'unsil', name: 'Universitas Siliwangi', type: 'university'),
    AffiliationModel(id: 'unterbuka', name: 'Universitas Terbuka', type: 'university'),
    AffiliationModel(id: 'upn', name: 'UPN Veteran Jakarta', type: 'university'),
    // Indonesia — Private
    AffiliationModel(id: 'binus', name: 'BINUS University', type: 'university'),
    AffiliationModel(id: 'telkom-u', name: 'Telkom University', type: 'university'),
    AffiliationModel(id: 'trisakti', name: 'Universitas Trisakti', type: 'university'),
    AffiliationModel(id: 'atma-jaya', name: 'Universitas Atma Jaya', type: 'university'),
    AffiliationModel(id: 'uph', name: 'Universitas Pelita Harapan', type: 'university'),
    AffiliationModel(id: 'petra', name: 'Universitas Kristen Petra', type: 'university'),
    AffiliationModel(id: 'umy', name: 'Universitas Muhammadiyah Yogyakarta', type: 'university'),
    AffiliationModel(id: 'uad', name: 'Universitas Ahmad Dahlan', type: 'university'),
    AffiliationModel(id: 'uii', name: 'Universitas Islam Indonesia', type: 'university'),
    AffiliationModel(id: 'mercu-buana', name: 'Universitas Mercu Buana', type: 'university'),
    AffiliationModel(id: 'gunadarma', name: 'Universitas Gunadarma', type: 'university'),
    AffiliationModel(id: 'esa-unggul', name: 'Universitas Esa Unggul', type: 'university'),
    AffiliationModel(id: 'pancasila', name: 'Universitas Pancasila', type: 'university'),
    AffiliationModel(id: 'untar', name: 'Universitas Tarumanagara', type: 'university'),
    AffiliationModel(id: 'maranatha', name: 'Universitas Kristen Maranatha', type: 'university'),
    AffiliationModel(id: 'unpar', name: 'Universitas Katolik Parahyangan', type: 'university'),
    AffiliationModel(id: 'uin-jakarta', name: 'UIN Syarif Hidayatullah Jakarta', type: 'university'),
    AffiliationModel(id: 'uin-kalijaga', name: 'UIN Sunan Kalijaga', type: 'university'),
    AffiliationModel(id: 'uin-bandung', name: 'UIN Sunan Gunung Djati', type: 'university'),
    AffiliationModel(id: 'uin-semarang', name: 'UIN Walisongo', type: 'university'),
    AffiliationModel(id: 'uin-malang', name: 'UIN Maulana Malik Ibrahim', type: 'university'),
    AffiliationModel(id: 'president-u', name: 'President University', type: 'university'),
    AffiliationModel(id: 'prasetiya-mulya', name: 'Prasetiya Mulya University', type: 'university'),
    AffiliationModel(id: 'ciputra', name: 'Universitas Ciputra', type: 'university'),
    AffiliationModel(id: 'unpas', name: 'Universitas Pasundan', type: 'university'),
    AffiliationModel(id: 'unjani', name: 'Universitas Jenderal Achmad Yani', type: 'university'),
    AffiliationModel(id: 'unika', name: 'Unika Soegijapranata', type: 'university'),
    AffiliationModel(id: 'udinus', name: 'Universitas Dian Nuswantoro', type: 'university'),
    AffiliationModel(id: 'unissula', name: 'Universitas Islam Sultan Agung', type: 'university'),
    AffiliationModel(id: 'unisma', name: 'Universitas Islam Malang', type: 'university'),
    AffiliationModel(id: 'ukdw', name: 'Universitas Kristen Duta Wacana', type: 'university'),
    AffiliationModel(id: 'uksw', name: 'Universitas Kristen Satya Wacana', type: 'university'),
    AffiliationModel(id: 'uhamka', name: 'Universitas Muhammadiyah Prof. Dr. HAMKA', type: 'university'),
    AffiliationModel(id: 'ums-surakarta', name: 'Universitas Muhammadiyah Surakarta', type: 'university'),
    AffiliationModel(id: 'umm-malang', name: 'Universitas Muhammadiyah Malang', type: 'university'),
    AffiliationModel(id: 'polban', name: 'Politeknik Negeri Bandung', type: 'university'),
    AffiliationModel(id: 'polinema', name: 'Politeknik Negeri Malang', type: 'university'),
    // Thailand
    AffiliationModel(id: 'chula', name: 'Chulalongkorn University', type: 'university'),
    AffiliationModel(id: 'mahidol', name: 'Mahidol University', type: 'university'),
    AffiliationModel(id: 'tu', name: 'Thammasat University', type: 'university'),
    AffiliationModel(id: 'ku', name: 'Kasetsart University', type: 'university'),
    AffiliationModel(id: 'cmu', name: 'Chiang Mai University', type: 'university'),
    AffiliationModel(id: 'kku', name: 'Khon Kaen University', type: 'university'),
    AffiliationModel(id: 'psu', name: 'Prince of Songkla University', type: 'university'),
    AffiliationModel(id: 'silpakorn', name: 'Silpakorn University', type: 'university'),
    AffiliationModel(id: 'buu', name: 'Burapha University', type: 'university'),
    AffiliationModel(id: 'kmitl', name: "King Mongkut's Institute of Technology Ladkrabang", type: 'university'),
    AffiliationModel(id: 'kmutt', name: "King Mongkut's University of Technology Thonburi", type: 'university'),
    AffiliationModel(id: 'kmutnb', name: "King Mongkut's University of Technology North Bangkok", type: 'university'),
    AffiliationModel(id: 'ait', name: 'Asian Institute of Technology', type: 'university'),
    AffiliationModel(id: 'swu', name: 'Srinakharinwirot University', type: 'university'),
    AffiliationModel(id: 'naresuan', name: 'Naresuan University', type: 'university'),
    AffiliationModel(id: 'mahasarakham', name: 'Mahasarakham University', type: 'university'),
    AffiliationModel(id: 'bangkok-u', name: 'Bangkok University', type: 'university'),
    AffiliationModel(id: 'assumption-u', name: 'Assumption University', type: 'university'),
    AffiliationModel(id: 'rangsit', name: 'Rangsit University', type: 'university'),
    AffiliationModel(id: 'ramkhamhaeng', name: 'Ramkhamhaeng University', type: 'university'),
    // Philippines
    AffiliationModel(id: 'up-diliman', name: 'University of the Philippines Diliman', type: 'university'),
    AffiliationModel(id: 'up-manila', name: 'UP Manila', type: 'university'),
    AffiliationModel(id: 'up-lb', name: 'UP Los Baños', type: 'university'),
    AffiliationModel(id: 'upv', name: 'UP Visayas', type: 'university'),
    AffiliationModel(id: 'admu', name: 'Ateneo de Manila University', type: 'university'),
    AffiliationModel(id: 'dlsu', name: 'De La Salle University', type: 'university'),
    AffiliationModel(id: 'ust', name: 'University of Santo Tomas', type: 'university'),
    AffiliationModel(id: 'feu', name: 'Far Eastern University', type: 'university'),
    AffiliationModel(id: 'nu-ph', name: 'National University Philippines', type: 'university'),
    AffiliationModel(id: 'adamson', name: 'Adamson University', type: 'university'),
    AffiliationModel(id: 'mapua', name: 'Mapúa University', type: 'university'),
    AffiliationModel(id: 'pup', name: 'Polytechnic University of the Philippines', type: 'university'),
    AffiliationModel(id: 'tip', name: 'Technological Institute of the Philippines', type: 'university'),
    AffiliationModel(id: 'usc-cebu', name: 'University of San Carlos', type: 'university'),
    AffiliationModel(id: 'silliman', name: 'Silliman University', type: 'university'),
    AffiliationModel(id: 'ateneo-cebu', name: 'Ateneo de Cebu', type: 'university'),
    AffiliationModel(id: 'xavier', name: 'Xavier University', type: 'university'),
    AffiliationModel(id: 'msu-marawi', name: 'Mindanao State University', type: 'university'),
    AffiliationModel(id: 'benilde', name: 'De La Salle–College of Saint Benilde', type: 'university'),
    AffiliationModel(id: 'ceu', name: 'Centro Escolar University', type: 'university'),
    AffiliationModel(id: 'lpu', name: 'Lyceum of the Philippines University', type: 'university'),
    AffiliationModel(id: 'san-beda', name: 'San Beda University', type: 'university'),
    // Vietnam
    AffiliationModel(id: 'vnu-hn', name: 'Vietnam National University Hanoi', type: 'university'),
    AffiliationModel(id: 'vnu-hcm', name: 'Vietnam National University HCMC', type: 'university'),
    AffiliationModel(id: 'hust', name: 'Hanoi University of Science and Technology', type: 'university'),
    AffiliationModel(id: 'ftu', name: 'Foreign Trade University', type: 'university'),
    AffiliationModel(id: 'neu', name: 'National Economics University', type: 'university'),
    AffiliationModel(id: 'hmu', name: 'Hanoi Medical University', type: 'university'),
    AffiliationModel(id: 'hcmut', name: 'HCMC University of Technology', type: 'university'),
    AffiliationModel(id: 'ueh', name: 'University of Economics HCMC', type: 'university'),
    AffiliationModel(id: 'hcmus', name: 'HCMC University of Science', type: 'university'),
    AffiliationModel(id: 'rmit-vn', name: 'RMIT Vietnam', type: 'university'),
    AffiliationModel(id: 'fulbright', name: 'Fulbright University Vietnam', type: 'university'),
    AffiliationModel(id: 'tdt', name: 'Ton Duc Thang University', type: 'university'),
    AffiliationModel(id: 'duy-tan', name: 'Duy Tan University', type: 'university'),
    AffiliationModel(id: 'hue-u', name: 'Hue University', type: 'university'),
    AffiliationModel(id: 'ctu', name: 'Can Tho University', type: 'university'),
    AffiliationModel(id: 'udn', name: 'University of Da Nang', type: 'university'),
    AffiliationModel(id: 'fpt', name: 'FPT University', type: 'university'),
    AffiliationModel(id: 'tmu', name: 'Thuong Mai University', type: 'university'),
    // Brunei / Cambodia / Myanmar / Laos / Timor-Leste
    AffiliationModel(id: 'ubd', name: 'Universiti Brunei Darussalam', type: 'university'),
    AffiliationModel(id: 'itb-bn', name: 'Institut Teknologi Brunei', type: 'university'),
    AffiliationModel(id: 'unissa', name: 'Universiti Islam Sultan Sharif Ali', type: 'university'),
    AffiliationModel(id: 'kupu-sb', name: 'KUPU SB', type: 'university'),
    AffiliationModel(id: 'rupp', name: 'Royal University of Phnom Penh', type: 'university'),
    AffiliationModel(id: 'rule', name: 'Royal University of Law and Economics', type: 'university'),
    AffiliationModel(id: 'rua', name: 'Royal University of Agriculture', type: 'university'),
    AffiliationModel(id: 'itc-kh', name: 'Institute of Technology of Cambodia', type: 'university'),
    AffiliationModel(id: 'norton', name: 'Norton University', type: 'university'),
    AffiliationModel(id: 'paragon', name: 'Paragon International University', type: 'university'),
    AffiliationModel(id: 'aeu-kh', name: 'Asia Europe University', type: 'university'),
    AffiliationModel(id: 'pannasastra', name: 'Pannasastra University of Cambodia', type: 'university'),
    AffiliationModel(id: 'u-yangon', name: 'University of Yangon', type: 'university'),
    AffiliationModel(id: 'u-mandalay', name: 'University of Mandalay', type: 'university'),
    AffiliationModel(id: 'yueco', name: 'Yangon University of Economics', type: 'university'),
    AffiliationModel(id: 'mtu', name: 'Mandalay Technological University', type: 'university'),
    AffiliationModel(id: 'nuol', name: 'National University of Laos', type: 'university'),
    AffiliationModel(id: 'souphanouvong', name: 'Souphanouvong University', type: 'university'),
    AffiliationModel(id: 'savannakhet-u', name: 'Savannakhet University', type: 'university'),
    AffiliationModel(id: 'champasak', name: 'Champasak University', type: 'university'),
    AffiliationModel(id: 'untl', name: "Universidade Nacional Timor Lorosa'e", type: 'university'),
    AffiliationModel(id: 'unpaz', name: 'Universidade da Paz', type: 'university'),
    AffiliationModel(id: 'dit', name: 'Dili Institute of Technology', type: 'university'),
    // Cities
    AffiliationModel(id: 'kl', name: 'Kuala Lumpur', type: 'city'),
    AffiliationModel(id: 'pj', name: 'Petaling Jaya', type: 'city'),
    AffiliationModel(id: 'shah_alam', name: 'Shah Alam', type: 'city'),
    AffiliationModel(id: 'subang', name: 'Subang Jaya', type: 'city'),
    AffiliationModel(id: 'klang', name: 'Klang', type: 'city'),
    AffiliationModel(id: 'jb', name: 'Johor Bahru', type: 'city'),
    AffiliationModel(id: 'iskandar', name: 'Iskandar Puteri', type: 'city'),
    AffiliationModel(id: 'penang', name: 'Penang', type: 'city'),
    AffiliationModel(id: 'ipoh', name: 'Ipoh', type: 'city'),
    AffiliationModel(id: 'melaka', name: 'Melaka', type: 'city'),
    AffiliationModel(id: 'kk', name: 'Kota Kinabalu', type: 'city'),
    AffiliationModel(id: 'kuching', name: 'Kuching', type: 'city'),
    AffiliationModel(id: 'miri', name: 'Miri', type: 'city'),
    AffiliationModel(id: 'sandakan', name: 'Sandakan', type: 'city'),
    AffiliationModel(id: 'tawau', name: 'Tawau', type: 'city'),
    AffiliationModel(id: 'kota_bharu', name: 'Kota Bharu', type: 'city'),
    AffiliationModel(id: 'kuala_terengganu', name: 'Kuala Terengganu', type: 'city'),
    AffiliationModel(id: 'kuantan', name: 'Kuantan', type: 'city'),
    AffiliationModel(id: 'alor_setar', name: 'Alor Setar', type: 'city'),
    AffiliationModel(id: 'seremban', name: 'Seremban', type: 'city'),
    AffiliationModel(id: 'putrajaya', name: 'Putrajaya', type: 'city'),
    AffiliationModel(id: 'cyberjaya', name: 'Cyberjaya', type: 'city'),
    AffiliationModel(id: 'bangi', name: 'Bangi', type: 'city'),
    AffiliationModel(id: 'kajang', name: 'Kajang', type: 'city'),
    AffiliationModel(id: 'nilai-city', name: 'Nilai', type: 'city'),
    AffiliationModel(id: 'taiping', name: 'Taiping', type: 'city'),
    AffiliationModel(id: 'muar', name: 'Muar', type: 'city'),
    AffiliationModel(id: 'batu_pahat', name: 'Batu Pahat', type: 'city'),
    AffiliationModel(id: 'labuan', name: 'Labuan', type: 'city'),
    AffiliationModel(id: 'singapore', name: 'Singapore', type: 'city'),
    AffiliationModel(id: 'jurong', name: 'Jurong', type: 'city'),
    AffiliationModel(id: 'woodlands', name: 'Woodlands', type: 'city'),
    AffiliationModel(id: 'tampines', name: 'Tampines', type: 'city'),
    AffiliationModel(id: 'jakarta', name: 'Jakarta', type: 'city'),
    AffiliationModel(id: 'surabaya', name: 'Surabaya', type: 'city'),
    AffiliationModel(id: 'bandung', name: 'Bandung', type: 'city'),
    AffiliationModel(id: 'medan', name: 'Medan', type: 'city'),
    AffiliationModel(id: 'semarang', name: 'Semarang', type: 'city'),
    AffiliationModel(id: 'makassar', name: 'Makassar', type: 'city'),
    AffiliationModel(id: 'palembang', name: 'Palembang', type: 'city'),
    AffiliationModel(id: 'tangerang', name: 'Tangerang', type: 'city'),
    AffiliationModel(id: 'bekasi', name: 'Bekasi', type: 'city'),
    AffiliationModel(id: 'depok', name: 'Depok', type: 'city'),
    AffiliationModel(id: 'bogor', name: 'Bogor', type: 'city'),
    AffiliationModel(id: 'batam', name: 'Batam', type: 'city'),
    AffiliationModel(id: 'pekanbaru', name: 'Pekanbaru', type: 'city'),
    AffiliationModel(id: 'padang', name: 'Padang', type: 'city'),
    AffiliationModel(id: 'malang', name: 'Malang', type: 'city'),
    AffiliationModel(id: 'yogyakarta', name: 'Yogyakarta', type: 'city'),
    AffiliationModel(id: 'solo', name: 'Solo (Surakarta)', type: 'city'),
    AffiliationModel(id: 'denpasar', name: 'Denpasar', type: 'city'),
    AffiliationModel(id: 'banjarmasin', name: 'Banjarmasin', type: 'city'),
    AffiliationModel(id: 'pontianak', name: 'Pontianak', type: 'city'),
    AffiliationModel(id: 'samarinda', name: 'Samarinda', type: 'city'),
    AffiliationModel(id: 'balikpapan', name: 'Balikpapan', type: 'city'),
    AffiliationModel(id: 'manado', name: 'Manado', type: 'city'),
    AffiliationModel(id: 'mataram', name: 'Mataram', type: 'city'),
    AffiliationModel(id: 'kupang', name: 'Kupang', type: 'city'),
    AffiliationModel(id: 'jayapura', name: 'Jayapura', type: 'city'),
    AffiliationModel(id: 'banda_aceh', name: 'Banda Aceh', type: 'city'),
    AffiliationModel(id: 'bandar_lampung', name: 'Bandar Lampung', type: 'city'),
    AffiliationModel(id: 'jambi', name: 'Jambi', type: 'city'),
    AffiliationModel(id: 'palu', name: 'Palu', type: 'city'),
    AffiliationModel(id: 'kendari', name: 'Kendari', type: 'city'),
    AffiliationModel(id: 'ambon', name: 'Ambon', type: 'city'),
    AffiliationModel(id: 'bangkok', name: 'Bangkok', type: 'city'),
    AffiliationModel(id: 'chiang_mai', name: 'Chiang Mai', type: 'city'),
    AffiliationModel(id: 'chiang_rai', name: 'Chiang Rai', type: 'city'),
    AffiliationModel(id: 'phuket', name: 'Phuket', type: 'city'),
    AffiliationModel(id: 'pattaya', name: 'Pattaya', type: 'city'),
    AffiliationModel(id: 'nonthaburi', name: 'Nonthaburi', type: 'city'),
    AffiliationModel(id: 'hat_yai', name: 'Hat Yai', type: 'city'),
    AffiliationModel(id: 'khon_kaen-city', name: 'Khon Kaen', type: 'city'),
    AffiliationModel(id: 'korat', name: 'Nakhon Ratchasima', type: 'city'),
    AffiliationModel(id: 'udon_thani', name: 'Udon Thani', type: 'city'),
    AffiliationModel(id: 'surat_thani', name: 'Surat Thani', type: 'city'),
    AffiliationModel(id: 'ubon-city', name: 'Ubon Ratchathani', type: 'city'),
    AffiliationModel(id: 'ayutthaya', name: 'Ayutthaya', type: 'city'),
    AffiliationModel(id: 'chonburi', name: 'Chonburi', type: 'city'),
    AffiliationModel(id: 'rayong', name: 'Rayong', type: 'city'),
    AffiliationModel(id: 'hua_hin', name: 'Hua Hin', type: 'city'),
    AffiliationModel(id: 'samui', name: 'Ko Samui', type: 'city'),
    AffiliationModel(id: 'krabi', name: 'Krabi', type: 'city'),
    AffiliationModel(id: 'manila', name: 'Manila', type: 'city'),
    AffiliationModel(id: 'quezon_city', name: 'Quezon City', type: 'city'),
    AffiliationModel(id: 'davao', name: 'Davao', type: 'city'),
    AffiliationModel(id: 'cebu', name: 'Cebu', type: 'city'),
    AffiliationModel(id: 'caloocan', name: 'Caloocan', type: 'city'),
    AffiliationModel(id: 'zamboanga', name: 'Zamboanga', type: 'city'),
    AffiliationModel(id: 'taguig', name: 'Taguig', type: 'city'),
    AffiliationModel(id: 'makati', name: 'Makati', type: 'city'),
    AffiliationModel(id: 'pasig', name: 'Pasig', type: 'city'),
    AffiliationModel(id: 'antipolo', name: 'Antipolo', type: 'city'),
    AffiliationModel(id: 'cdo', name: 'Cagayan de Oro', type: 'city'),
    AffiliationModel(id: 'iloilo', name: 'Iloilo', type: 'city'),
    AffiliationModel(id: 'bacolod', name: 'Bacolod', type: 'city'),
    AffiliationModel(id: 'baguio', name: 'Baguio', type: 'city'),
    AffiliationModel(id: 'angeles', name: 'Angeles', type: 'city'),
    AffiliationModel(id: 'naga', name: 'Naga', type: 'city'),
    AffiliationModel(id: 'legazpi', name: 'Legazpi', type: 'city'),
    AffiliationModel(id: 'tacloban', name: 'Tacloban', type: 'city'),
    AffiliationModel(id: 'dumaguete', name: 'Dumaguete', type: 'city'),
    AffiliationModel(id: 'puerto_princesa', name: 'Puerto Princesa', type: 'city'),
    AffiliationModel(id: 'gensan', name: 'General Santos', type: 'city'),
    AffiliationModel(id: 'hanoi', name: 'Hanoi', type: 'city'),
    AffiliationModel(id: 'hcmc', name: 'Ho Chi Minh City', type: 'city'),
    AffiliationModel(id: 'da_nang', name: 'Da Nang', type: 'city'),
    AffiliationModel(id: 'hai_phong', name: 'Hai Phong', type: 'city'),
    AffiliationModel(id: 'can_tho', name: 'Can Tho', type: 'city'),
    AffiliationModel(id: 'nha_trang', name: 'Nha Trang', type: 'city'),
    AffiliationModel(id: 'da_lat', name: 'Da Lat', type: 'city'),
    AffiliationModel(id: 'hue-city', name: 'Hue', type: 'city'),
    AffiliationModel(id: 'vung_tau', name: 'Vung Tau', type: 'city'),
    AffiliationModel(id: 'quy_nhon', name: 'Quy Nhon', type: 'city'),
    AffiliationModel(id: 'phu_quoc', name: 'Phu Quoc', type: 'city'),
    AffiliationModel(id: 'hoi_an', name: 'Hoi An', type: 'city'),
    AffiliationModel(id: 'bsb', name: 'Bandar Seri Begawan', type: 'city'),
    AffiliationModel(id: 'kuala_belait', name: 'Kuala Belait', type: 'city'),
    AffiliationModel(id: 'phnom_penh', name: 'Phnom Penh', type: 'city'),
    AffiliationModel(id: 'siem_reap', name: 'Siem Reap', type: 'city'),
    AffiliationModel(id: 'battambang', name: 'Battambang', type: 'city'),
    AffiliationModel(id: 'sihanoukville', name: 'Sihanoukville', type: 'city'),
    AffiliationModel(id: 'yangon', name: 'Yangon', type: 'city'),
    AffiliationModel(id: 'mandalay', name: 'Mandalay', type: 'city'),
    AffiliationModel(id: 'naypyidaw', name: 'Naypyidaw', type: 'city'),
    AffiliationModel(id: 'taunggyi', name: 'Taunggyi', type: 'city'),
    AffiliationModel(id: 'vientiane', name: 'Vientiane', type: 'city'),
    AffiliationModel(id: 'luang_prabang', name: 'Luang Prabang', type: 'city'),
    AffiliationModel(id: 'pakse', name: 'Pakse', type: 'city'),
    AffiliationModel(id: 'dili', name: 'Dili', type: 'city'),
    AffiliationModel(id: 'baucau', name: 'Baucau', type: 'city'),
    // Interests
    AffiliationModel(id: 'kpop', name: 'K-Pop', type: 'interest'),
    AffiliationModel(id: 'jpop', name: 'J-Pop', type: 'interest'),
    AffiliationModel(id: 'anime', name: 'Anime', type: 'interest'),
    AffiliationModel(id: 'manga', name: 'Manga', type: 'interest'),
    AffiliationModel(id: 'gaming', name: 'Gaming', type: 'interest'),
    AffiliationModel(id: 'esports', name: 'E-sports', type: 'interest'),
    AffiliationModel(id: 'football', name: 'Football', type: 'interest'),
    AffiliationModel(id: 'futsal', name: 'Futsal', type: 'interest'),
    AffiliationModel(id: 'basketball', name: 'Basketball', type: 'interest'),
    AffiliationModel(id: 'volleyball', name: 'Volleyball', type: 'interest'),
    AffiliationModel(id: 'badminton', name: 'Badminton', type: 'interest'),
    AffiliationModel(id: 'tennis', name: 'Tennis', type: 'interest'),
    AffiliationModel(id: 'swimming', name: 'Swimming', type: 'interest'),
    AffiliationModel(id: 'athletics', name: 'Athletics', type: 'interest'),
    AffiliationModel(id: 'martial_arts', name: 'Martial Arts', type: 'interest'),
    AffiliationModel(id: 'boxing', name: 'Boxing', type: 'interest'),
    AffiliationModel(id: 'muay_thai', name: 'Muay Thai', type: 'interest'),
    AffiliationModel(id: 'silat', name: 'Silat', type: 'interest'),
    AffiliationModel(id: 'taekwondo', name: 'Taekwondo', type: 'interest'),
    AffiliationModel(id: 'gym', name: 'Gym & Fitness', type: 'interest'),
    AffiliationModel(id: 'running', name: 'Running', type: 'interest'),
    AffiliationModel(id: 'cycling', name: 'Cycling', type: 'interest'),
    AffiliationModel(id: 'hiking', name: 'Hiking', type: 'interest'),
    AffiliationModel(id: 'climbing', name: 'Climbing', type: 'interest'),
    AffiliationModel(id: 'surfing', name: 'Surfing', type: 'interest'),
    AffiliationModel(id: 'skateboarding', name: 'Skateboarding', type: 'interest'),
    AffiliationModel(id: 'dance', name: 'Dance', type: 'interest'),
    AffiliationModel(id: 'hiphop', name: 'Hip-Hop', type: 'interest'),
    AffiliationModel(id: 'kdrama', name: 'K-Drama', type: 'interest'),
    AffiliationModel(id: 'movies', name: 'Movies', type: 'interest'),
    AffiliationModel(id: 'series', name: 'Series Binge', type: 'interest'),
    AffiliationModel(id: 'music', name: 'Music', type: 'interest'),
    AffiliationModel(id: 'singing', name: 'Singing', type: 'interest'),
    AffiliationModel(id: 'guitar', name: 'Guitar', type: 'interest'),
    AffiliationModel(id: 'piano', name: 'Piano', type: 'interest'),
    AffiliationModel(id: 'djing', name: 'DJing', type: 'interest'),
    AffiliationModel(id: 'producing', name: 'Music Producing', type: 'interest'),
    AffiliationModel(id: 'art', name: 'Art', type: 'interest'),
    AffiliationModel(id: 'drawing', name: 'Drawing', type: 'interest'),
    AffiliationModel(id: 'painting', name: 'Painting', type: 'interest'),
    AffiliationModel(id: 'photography', name: 'Photography', type: 'interest'),
    AffiliationModel(id: 'videography', name: 'Videography', type: 'interest'),
    AffiliationModel(id: 'design', name: 'Design', type: 'interest'),
    AffiliationModel(id: 'fashion', name: 'Fashion', type: 'interest'),
    AffiliationModel(id: 'thrifting', name: 'Thrifting', type: 'interest'),
    AffiliationModel(id: 'makeup', name: 'Makeup', type: 'interest'),
    AffiliationModel(id: 'cooking', name: 'Cooking', type: 'interest'),
    AffiliationModel(id: 'baking', name: 'Baking', type: 'interest'),
    AffiliationModel(id: 'foodie', name: 'Foodie', type: 'interest'),
    AffiliationModel(id: 'coffee', name: 'Coffee', type: 'interest'),
    AffiliationModel(id: 'tea', name: 'Tea', type: 'interest'),
    AffiliationModel(id: 'street_food', name: 'Street Food', type: 'interest'),
    AffiliationModel(id: 'travel', name: 'Travel', type: 'interest'),
    AffiliationModel(id: 'backpacking', name: 'Backpacking', type: 'interest'),
    AffiliationModel(id: 'volunteering', name: 'Volunteering', type: 'interest'),
    AffiliationModel(id: 'coding', name: 'Coding', type: 'interest'),
    AffiliationModel(id: 'ai', name: 'AI & ML', type: 'interest'),
    AffiliationModel(id: 'startups', name: 'Startups', type: 'interest'),
    AffiliationModel(id: 'finance', name: 'Finance', type: 'interest'),
    AffiliationModel(id: 'investing', name: 'Investing', type: 'interest'),
    AffiliationModel(id: 'crypto', name: 'Crypto', type: 'interest'),
    AffiliationModel(id: 'business', name: 'Business', type: 'interest'),
    AffiliationModel(id: 'marketing', name: 'Marketing', type: 'interest'),
    AffiliationModel(id: 'law', name: 'Law', type: 'interest'),
    AffiliationModel(id: 'medicine', name: 'Medicine', type: 'interest'),
    AffiliationModel(id: 'nursing', name: 'Nursing', type: 'interest'),
    AffiliationModel(id: 'engineering', name: 'Engineering', type: 'interest'),
    AffiliationModel(id: 'science', name: 'Science', type: 'interest'),
    AffiliationModel(id: 'math', name: 'Math', type: 'interest'),
    AffiliationModel(id: 'debate', name: 'Debate', type: 'interest'),
    AffiliationModel(id: 'public_speaking', name: 'Public Speaking', type: 'interest'),
    AffiliationModel(id: 'writing', name: 'Writing', type: 'interest'),
    AffiliationModel(id: 'poetry', name: 'Poetry', type: 'interest'),
    AffiliationModel(id: 'books', name: 'Books', type: 'interest'),
    AffiliationModel(id: 'board_games', name: 'Board Games', type: 'interest'),
    AffiliationModel(id: 'chess', name: 'Chess', type: 'interest'),
    AffiliationModel(id: 'cosplay', name: 'Cosplay', type: 'interest'),
    AffiliationModel(id: 'cars', name: 'Cars', type: 'interest'),
    AffiliationModel(id: 'bikes', name: 'Bikes', type: 'interest'),
    AffiliationModel(id: 'evs', name: 'EVs', type: 'interest'),
    AffiliationModel(id: 'astronomy', name: 'Astronomy', type: 'interest'),
    AffiliationModel(id: 'environment', name: 'Environment', type: 'interest'),
    AffiliationModel(id: 'sustainability', name: 'Sustainability', type: 'interest'),
    AffiliationModel(id: 'pets', name: 'Pets', type: 'interest'),
    AffiliationModel(id: 'cats', name: 'Cats', type: 'interest'),
    AffiliationModel(id: 'dogs', name: 'Dogs', type: 'interest'),
    AffiliationModel(id: 'gardening', name: 'Gardening', type: 'interest'),
    AffiliationModel(id: 'diy', name: 'DIY', type: 'interest'),
    AffiliationModel(id: 'crafts', name: 'Crafts', type: 'interest'),
  ];
}
