import '../models/affiliation_model.dart';

class AffiliationsSeed {
  static const List<AffiliationModel> affiliations = [
    // Universities (18+)
    AffiliationModel(id: 'um', name: 'University of Malaya', type: 'university'),
    AffiliationModel(id: 'usm', name: 'Universiti Sains Malaysia', type: 'university'),
    AffiliationModel(id: 'utm', name: 'Universiti Teknologi Malaysia', type: 'university'),
    AffiliationModel(id: 'ukm', name: 'Universiti Kebangsaan Malaysia', type: 'university'),
    AffiliationModel(id: 'taylors', name: "Taylor's University", type: 'university'),
    AffiliationModel(id: 'sunway', name: 'Sunway University', type: 'university'),
    AffiliationModel(id: 'monash-my', name: 'Monash University Malaysia', type: 'university'),
    AffiliationModel(id: 'ucsi', name: 'UCSI University', type: 'university'),
    AffiliationModel(id: 'uitm', name: 'UiTM', type: 'university'),
    AffiliationModel(id: 'apu', name: 'APU', type: 'university'),
    AffiliationModel(id: 'inti', name: 'INTI International', type: 'university'),
    AffiliationModel(id: 'mmu', name: 'Multimedia University', type: 'university'),
    AffiliationModel(id: 'utar', name: 'UTAR', type: 'university'),
    AffiliationModel(id: 'help', name: 'HELP University', type: 'university'),
    AffiliationModel(id: 'ui', name: 'Universitas Indonesia', type: 'university'),
    AffiliationModel(id: 'binus', name: 'BINUS', type: 'university'),
    AffiliationModel(id: 'ugm', name: 'UGM', type: 'university'),
    AffiliationModel(id: 'itb', name: 'ITB', type: 'university'),
    AffiliationModel(id: 'nus', name: 'NUS', type: 'university'),
    AffiliationModel(id: 'ntu', name: 'NTU', type: 'university'),
    AffiliationModel(id: 'chula', name: 'Chulalongkorn', type: 'university'),
    AffiliationModel(id: 'mahidol', name: 'Mahidol', type: 'university'),
    AffiliationModel(id: 'upd', name: 'UP Diliman', type: 'university'),
    AffiliationModel(id: 'ateneo', name: 'Ateneo', type: 'university'),
    AffiliationModel(id: 'dlsu', name: 'De La Salle', type: 'university'),
    AffiliationModel(id: 'hcmut', name: 'HCMUT', type: 'university'),
    AffiliationModel(id: 'vnu', name: 'VNU Hanoi', type: 'university'),
    AffiliationModel(id: 'fpt', name: 'FPT University', type: 'university'),
    
    // Cities (15+)
    AffiliationModel(id: 'kl', name: 'Kuala Lumpur', type: 'city'),
    AffiliationModel(id: 'pj', name: 'Petaling Jaya', type: 'city'),
    AffiliationModel(id: 'shah_alam', name: 'Shah Alam', type: 'city'),
    AffiliationModel(id: 'penang', name: 'Penang', type: 'city'),
    AffiliationModel(id: 'jb', name: 'Johor Bahru', type: 'city'),
    AffiliationModel(id: 'ipoh', name: 'Ipoh', type: 'city'),
    AffiliationModel(id: 'melaka', name: 'Melaka', type: 'city'),
    AffiliationModel(id: 'kk', name: 'Kota Kinabalu', type: 'city'),
    AffiliationModel(id: 'kuching', name: 'Kuching', type: 'city'),
    AffiliationModel(id: 'jakarta', name: 'Jakarta', type: 'city'),
    AffiliationModel(id: 'bandung', name: 'Bandung', type: 'city'),
    AffiliationModel(id: 'surabaya', name: 'Surabaya', type: 'city'),
    AffiliationModel(id: 'yogyakarta', name: 'Yogyakarta', type: 'city'),
    AffiliationModel(id: 'singapore', name: 'Singapore', type: 'city'),
    AffiliationModel(id: 'bangkok', name: 'Bangkok', type: 'city'),
    AffiliationModel(id: 'chiang_mai', name: 'Chiang Mai', type: 'city'),
    AffiliationModel(id: 'manila', name: 'Manila', type: 'city'),
    AffiliationModel(id: 'quezon', name: 'Quezon City', type: 'city'),
    AffiliationModel(id: 'cebu', name: 'Cebu', type: 'city'),
    AffiliationModel(id: 'hcmc', name: 'Ho Chi Minh City', type: 'city'),
    AffiliationModel(id: 'hanoi', name: 'Hanoi', type: 'city'),
    AffiliationModel(id: 'da_nang', name: 'Da Nang', type: 'city'),
    
    // Interests (12+)
    AffiliationModel(id: 'cs', name: 'Computer Science', type: 'interest'),
    AffiliationModel(id: 'mental_health', name: 'Mental Health', type: 'interest'),
    AffiliationModel(id: 'gaming', name: 'Gaming', type: 'interest'),
    AffiliationModel(id: 'music', name: 'Music', type: 'interest'),
    AffiliationModel(id: 'anime', name: 'Anime & Manga', type: 'interest'),
    AffiliationModel(id: 'sports', name: 'Sports', type: 'interest'),
    AffiliationModel(id: 'fitness', name: 'Fitness', type: 'interest'),
    AffiliationModel(id: 'art', name: 'Art & Design', type: 'interest'),
    AffiliationModel(id: 'food', name: 'Food & Cafe Hopping', type: 'interest'),
    AffiliationModel(id: 'movies', name: 'Movies & Series', type: 'interest'),
    AffiliationModel(id: 'fashion', name: 'Fashion', type: 'interest'),
    AffiliationModel(id: 'tech', name: 'Tech & Startups', type: 'interest'),
    AffiliationModel(id: 'photography', name: 'Photography', type: 'interest'),
    AffiliationModel(id: 'kpop', name: 'K-Pop', type: 'interest'),
    AffiliationModel(id: 'study_tips', name: 'Study Tips', type: 'interest'),
    AffiliationModel(id: 'exam_stress', name: 'Exam Stress', type: 'interest'),
  ];
}
