class CountriesSeed {
  static final List<String> countries = [
    'United States 🇺🇸',
    'Canada 🇨🇦',
    'Mexico 🇲🇽',
    'United Kingdom 🇬🇧',
    'Ireland 🇮🇪',
    'France 🇫🇷',
    'Germany 🇩🇪',
    'Spain 🇪🇸',
    'Italy 🇮🇹',
    'Portugal 🇵🇹',
    'Netherlands 🇳🇱',
    'Belgium 🇧🇪',
    'Switzerland 🇨🇭',
    'Austria 🇦🇹',
    'Sweden 🇸🇪',
    'Norway 🇳🇴',
    'Denmark 🇩🇰',
    'Finland 🇫🇮',
    'Poland 🇵🇱',
    'Greece 🇬🇷',
    'Turkey 🇹🇷',
    'Russia 🇷🇺',
    'Ukraine 🇺🇦',
    'Romania 🇷🇴',
    'Hungary 🇭🇺',
    'Czech Republic 🇨🇿',
    'Australia 🇦🇺',
    'New Zealand 🇳🇿',
    'Japan 🇯🇵',
    'China 🇨🇳',
    'South Korea 🇰🇷',
    'India 🇮🇳',
    'Pakistan 🇵🇰',
    'Bangladesh 🇧🇩',
    'Indonesia 🇮🇩',
    'Malaysia 🇲🇾',
    'Singapore 🇸🇬',
    'Thailand 🇹🇭',
    'Vietnam 🇻🇳',
    'Philippines 🇵🇭',
    'Brazil 🇧🇷',
    'Argentina 🇦🇷',
    'Chile 🇨🇱',
    'Colombia 🇨🇴',
    'Peru 🇵🇪',
    'South Africa 🇿🇦',
    'Nigeria 🇳🇬',
    'Egypt 🇪🇬',
    'Kenya 🇰🇪',
    'Morocco 🇲🇦',
    'Saudi Arabia 🇸🇦',
    'UAE 🇦🇪',
    'Iran 🇮🇷',
    'Iraq 🇮🇶',
  ];
}
